exports.POST_STATUS = {
  PENDING: 'PENDING',
  ACCEPT: 'ACCEPT',
  REJECT: 'REJECT',
  CANCEL: 'CANCEL',
  START: 'START'
};

exports.MATCH_STATUS = {
  PROGRESS: 'PROGRESS',
  DELIVER_CANCEL: 'DELIVER_CANCEL',
  DELIVER_DONE: 'DELIVER_DONE',
  RECEIVER_DONE: 'RECEIVER_DONE',
  DONE: 'DONE',
};
